### ISSUE TITLE
Issue index for axis

### ISSUE THREAD

**Issue by JulFIC** [beto-rodriguez/Live-Charts#319] opened 2016-08-29 09:58 UTC
Hello,
we have this error on Visual but we can't get more information...
Is it about the axis X or axis Y ?
How we can get more information ?

System.ArgumentOutOfRangeException: L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
Nom du paramètre : index
   à System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   à System.Collections.Generic.List`1.get_Item(Int32 index)
   à LiveCharts.ChartFunctions.ToPlotArea(Double value, AxisOrientation source, ChartCore chart, Int32 axis)
   à LiveCharts.ChartFunctions.ToDrawMargin(Double value, AxisOrientation source, ChartCore chart, Int32 axis)
   à LiveCharts.ChartFunctions.ToDrawMargin(ChartPoint point, Int32 axisXIndex, Int32 axisYIndex, ChartCore chart)
   à LiveCharts.SeriesAlgorithms.LineAlgorithm.Update()
   à LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
   à LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick(Boolean restartView)
   à LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
   à System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Thanks

**Comment by beto-rodriguez** [comment] 2016-08-31 03:11
Hello, what are the steps to reproduce this?

**Comment by beto-rodriguez** [comment] 2016-09-20 19:01
Closing this issue because there is not enough info, feel free to add any feedback or creating a new issue when you need

**Closed by beto-rodriguez** 2016-09-20 19:01 UTC
