### ISSUE TITLE
Line Series bound Y Axes not displayed after data template swap.

### ISSUE THREAD

**Issue by Stephen-Ross** [beto-rodriguez/Live-Charts#331] opened 2016-09-13 16:15 UTC
#### How to reproduce?

This issue occurs after a switch of DataTemplate's which each show different LiveChart displays.

On the first DataTemplate there is a Cartesian Chart which displays numerous LineSeries which have a bound 'AxisY' collection to the View Model, this Axis Collection is build up in the View Model from the different Line Series data sources. At first the Y Axes are displayed correctly:

![yaxes](https://cloud.githubusercontent.com/assets/22176150/18481475/3a275e78-79d4-11e6-8bec-3d9bfa369ee3.png)

But if I switch to another DataTemplate to display other data and switch back to the original view the Y Axes are not displayed:

![noyaxes](https://cloud.githubusercontent.com/assets/22176150/18481554/757fb682-79d4-11e6-883e-ceb23ac842c7.png)

Currently I build each of the Y Axes like so:

``` C#
new LiveCharts.Wpf.Axis
 {
    DataContext = this,
    MaxValue = axisModel.Max,
    MinValue = axisModel.Min
 };
```

And add them to the collection like so:

``` C#
this.axes = new AxesCollection();
this.axes.Add(dataSliceViewModel.LineSeries.YAxis.Axis);
```

I am binding to the `AxesCollection` in xaml like so:

``` C#
AxisY="{Binding Path=Axes}"
```

It should be noted that this behavior only occurs if the `AxisY` is bound to a collection on the View Model. If I simply have a Y Axis and bind it's Max and Min values it will be correctly displayed between switching of the Data Templates.
#### Extra notes

I would expect that the Graph would be correctly build after the switch of Data Templates especially if no changes were made to the underlying Axes after the Data Templates were swapped.

As said this only appears to occur if the `AxisY` is bound to a collection, and does not occur if the Axes are pre-configured.
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.13</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>7</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment] 2017-02-06 04:47
Hello, thanks for the report, I was not able to reproduce with latest, maybe it got fixed with a previous commit.

Am I doing it right?

```c#
namespace LiveChartsTesterGuy
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            if (ContentControl.ContentTemplate == null)
            {
                ContentControl.ContentTemplate = (DataTemplate) Grid.FindResource("Template1");
            }
            else
            {
                ContentControl.ContentTemplate = null;
            }
        }
    }

    public class Template1Vm
    {
        public Template1Vm()
        {
            AxesCollection = new AxesCollection
            {
                new Axis(),
                new Axis(),
                new Axis()
            };
        }

        public AxesCollection AxesCollection { get; set; }
    }
}
```

```xml
<Grid Name="Grid">
        <Grid.Resources>
            <DataTemplate x:Key="Template1">
                <lvc:CartesianChart AxisY="{Binding AxesCollection}">
                    <lvc:CartesianChart.DataContext>
                        <local:Template1Vm></local:Template1Vm>
                    </lvc:CartesianChart.DataContext>
                    <lvc:CartesianChart.Series>
                        <lvc:LineSeries Values="1,6,2" ScalesYAt="0"/>
                        <lvc:LineSeries Values="30,50,70" ScalesYAt="1"/>
                        <lvc:LineSeries Values="20,30,20" ScalesYAt="2"/>
                    </lvc:CartesianChart.Series>
                </lvc:CartesianChart>
            </DataTemplate>
        </Grid.Resources>
        <ContentControl Name="ContentControl"></ContentControl>
        <Button Click="ButtonBase_OnClick" VerticalAlignment="Top" HorizontalAlignment="Left">ToggleTemplate</Button>
    </Grid>
```

**Comment by beto-rodriguez** [comment] 2017-02-12 23:57
I am closing this issue since I am not able to reproduce.

Thanks for the report.

**Closed by beto-rodriguez** 2017-02-12 23:57 UTC
Labels: more info required, unconfirmed bug
