### ISSUE TITLE
[Ghost Markers] - After a Series.Values.Clear() the CartesianChart still shows the data markers.

### ISSUE THREAD

**Issue by EvripidesKarseras** [beto-rodriguez/Live-Charts#210] opened 2016-06-15 14:37 UTC
On a Cartesian chart with two series of type ObservablePoint (or other custom data type) that are being updated constantly, the marker points of the data still remain visible after the relevant series has been cleared and removed from the collection. The x axis limits are also being updated but it makes no difference to rectifying the bug. The issue disappears when using an int data type for the series.

![lvcharts_ghost_bug](https://cloud.githubusercontent.com/assets/3636613/16083958/d4809b22-330e-11e6-90d6-922a48667ed8.PNG)

**Comment by beto-rodriguez** [comment] 2016-06-15 14:41
Thanks for the report, fixing asap, an alternative for now is setting the LineSeries.PointDiameter to zero:

    LineSeries
    {
        Values = //..
        PointDiameter = 0
    }

**Comment by beto-rodriguez** [comment] 2016-06-18 00:28
I am not able to force this, can you please give me more info about it

**Comment by EvripidesKarseras** [comment] 2016-06-18 07:48
Hi Beto, the chart is basically being updated at a high rate via incoming ethernet packets,
cartesianchart.series[x].values.add(); 
if ....count > 100; ....removeat(0);

Say you have 2 series and at some point you attempt:
cartesianchart.series.removeat(1);
Then you have the ghost points of series 1 like in the image.

If the rate at which you update the graph is lowered then you never get this issue. I tried this by throttling the packet rate and it was OK.

I was not able to force this either with a timer as the fastest you can do is 1ms. Maybe it is simpler to do in a for loop which I haven't tried, i.e., create 2 series, add 2000 points in a loop, display 100 points in each series at a time and then at some for loop index suddenly remove one series. I might give this a go and see what happens.

Evros

**Comment by beto-rodriguez** [comment] 2016-07-14 20:18
#260 should also help this issue

**Comment by beto-rodriguez** [comment] 2016-08-05 15:25
closing this issue since we are close to 2 months now, and no one has confirmed it

**Closed by beto-rodriguez** 2016-08-05 15:25 UTC
Labels: unconfirmed bug

**Comment by Shadowmafia** [comment] 2018-07-08 15:06
Clear Points : https://github.com/Shadowmafia/First-MultiThreading-HomeWork-C-WPF-Graphs
In this project, in the OutputDiagram window ->RefreshChart ().
