### ISSUE TITLE
RowSeries with negative values

### ISSUE THREAD

**Issue by flabegalini** [beto-rodriguez/Live-Charts#401] opened 2016-11-23 11:29 UTC
Beto Rodriguez, at first, congratulations for LiveCharts. It´s amazing!
So...

How can I set negative values on Basic Rows?

Negative values are not showed on chart.

I'm using that:

        public TestChartControl()
        {
            InitializeComponent();

            cartesianChart1.Series = new SeriesCollection
            {
                new RowSeries
                {
                    Title = "2015",
                    Values = new ChartValues<double> { -10, -50, -39, -50 }
                }
            };

            //adding series will update and animate the chart automatically
            cartesianChart1.Series.Add(new RowSeries
            {
                Title = "2016",
                Values = new ChartValues<double> { 11, 56, 42 }
            });

            //also adding values updates and animates the chart automatically
            cartesianChart1.Series[1].Values.Add(48d);

            cartesianChart1.AxisY.Add(new Axis
            {
                Labels = new[] { "Maria", "Susan", "Charles", "Frida" }
            });

            cartesianChart1.AxisX.Add(new Axis
            {
                LabelFormatter = value => value.ToString("N")
                
            });

            var tooltip = new DefaultTooltip
            {
                SelectionMode = TooltipSelectionMode.SharedYValues
            };

            cartesianChart1.DataTooltip = tooltip;
        }

The result is:

![image](https://cloud.githubusercontent.com/assets/23698713/20560054/92bef7f0-b15e-11e6-8216-a816cd8031aa.png)

Thanks!

**Comment by rusanov-vladimir** [comment] 2016-11-23 12:21
Just some additional info:
It looks like it's a regression introduced in version 0.8 by this [line](https://github.com/beto-rodriguez/Live-Charts/blob/master/Core/SeriesAlgorithms/RowAlgorithm.cs#L96) in this [commit](https://github.com/beto-rodriguez/Live-Charts/commit/9856fa31d59ad8cda7c9199ae4e6eee067e09951). So basically if something is less then 0, it considered to be 0. Previously it line looked like this: `var w = Math.Abs(reference.X - zero);` and it still looks like this for ColumnAlgorithm(which works).

**Comment by beto-rodriguez** [comment] 2016-12-20 02:04
@flabegalini Thanks for the report and again thanks @rusanov-vladimir for your reply.

This issue is already solved, with the referenced commit, this fix will be included since version 0.8.1

**Closed** 2016-12-20 02:09 UTC
