### ISSUE TITLE
LiveCharts.Helpers.LiveChartsException when DisableAnimations = true

### ISSUE THREAD

**Issue by klem0810** [beto-rodriguez/Live-Charts#406] opened 2016-12-05 21:00 UTC
Hi, 

I'm getting an LiveCharts.Helpers.LiveChartsException when I try to set DisableAnimations = true using the Geared version of LiveCharts. DisableAnimations = false, works fine but is not responsive enough for me.

I tested the free version LiveCharts.Wpf 0.8.0.  and I did not get the same error. 

#### Here's the debugger message :
Impossible to get points from an not loaded already series, ensure the series is initialized before calling GetPoints() method.

Try the Livecharts.Geared 1.2.0 code below to reproduce the error. 

### Code Livecharts.Geared 1.2.0 (Bug)

var liveCharts = new CartesianChart() { DisableAnimations = true };

liveCharts.Series = new SeriesCollection {  new GLineSeries {                    
		Values = new GearedValues<double> {7,4,9} }  };

this.ChartGrid.Children.Add(liveCharts);

### Code LiveCharts.Wpf 0.8.0 (OK)

var liveCharts = new CartesianChart() { DisableAnimations = true };

liveCharts.Series = new SeriesCollection {  new LineSeries {
Values = new ChartValues<double> {7,4,9} }  };

this.ChartGrid.Children.Add(liveCharts);

**Comment by beto-rodriguez** [comment] 2016-12-06 17:44
Thanks for the report, fixing it asap

**Comment by klem0810** [comment] 2016-12-07 20:43
Thanks. Please, keep me informed when the issue is fixed

**Comment by smohnkern** [comment] 2017-01-04 18:09
I have run into the same issue and was wondering when this would be resolved.  With animation on and only 2016 points in each series, zooming and panning is extremely slow and unusable with animation set to true.  Unfortunately I will have to find another control soon to satisfy my delivery if I can't find a work around for this.  Thanks

**Comment by beto-rodriguez** [comment] 2017-01-04 18:30
Please take a read here https://lvcharts.net/App/examples/v1/wpf/Performance%20Tips 
You can also test your best configuration here https://lvcharts.net/content/exampleapp.zip

There are many things you can do to improve permanecer, we need LiveCharts flexible for any case, I recommend you to try it better, I am sure there are many things you can do to improve your plots

**Comment by smohnkern** [comment] 2017-01-04 18:36
Not sure what my issue is then because I am have not point graphics and I am adding series with single add as follows:

var livePressureData = new double[data.Length];                          
liveChartP.Series.Add(
        new LineSeries
         {
              Title = serName,
               PointGeometry = DefaultGeometries.None,
               LineSmoothness = 0,
               Fill = new SolidColorBrush(System.Windows.Media.Color.FromArgb(0, 0, 0, 0)),
               Stroke = null,
               StrokeThickness = 1,
               Values = livePressureData.AsGearedValues().WithQuality(Quality.Low)
          }
);

**Comment by smohnkern** [comment] 2017-01-04 18:37
Sorry for poor grammar....That was 'I am using the performance recommendations and I have no point graphics'

**Comment by smohnkern** [comment] 2017-01-04 18:43
Btw...It was working until I upgraded to your latest version.  I upgraded because I was having an issue when I turned on the Xy zoom.  This appears to work correctly now with latest libraries but now very slow.   I am using your chart in a Windows Forms project.  Thanks again for your help.

**Comment by beto-rodriguez** [comment] 2017-01-04 18:46
Thanks for your feedback, i'll be back once I test what you said, I am working to fix the geared bugs, I'll test what you mentioned, thanks again

**Comment by smohnkern** [comment] 2017-01-04 18:59
Thank you for your responsiveness.  Just so you are aware.  I changed your GearedExample source to use the latest libraries and had the same results.  I had to set DisableAnimations to false and it is very slow.  Just a glitch I am sure you will find.

**Comment by smohnkern** [comment] 2017-01-04 19:10
I apologize for the flood of emails but wanted to let you know that it is slow when DisableAnimations is set to false for the 0.7 versions as well.  If you can fix so this can be disabled for the latest version then I think I will be set.

**Comment by smohnkern** [comment] 2017-01-09 16:17
Any progress on this?   I need to select a graph for my client today and was hoping to show him LiveCharts in action.  Thanks

**Comment by beto-rodriguez** [comment] 2017-01-15 03:24
This but is already fixed and will be included in the next version of the geared version (1.2.5) thanks for reporting, i'll close the issue and let you know when the version is available in nuget

**Comment by beto-rodriguez** [comment] 2017-01-23 05:21
I am closing this issue, the version is already in Nuget, @smohnkern I was not able to reproduce your issue, ensure you are using the package correctly, this week there will be more available examples in the web site using the G
eared pacakge

**Closed by beto-rodriguez** 2017-01-23 05:21 UTC
