### ISSUE TITLE
Enhancement: Offscreen charts rendering

### ISSUE THREAD

**Issue by jeanluc-martin** [beto-rodriguez/Live-Charts#415] opened 2016-12-19 10:19 UTC
Hi,

In order du produce report, it will be great to have an offscreen mode.

If rendering a chart in a bitmap is easy when the chart is shown on the UI,
it seems impossible to render a chart outside the UI.

I try this without success (DisableAnimations="True"):
...
control.Measure(new Size(width, height));
control.Arrange(new Rect(new Size(width,height)));
RenderTargetBitmap bmp = new RenderTargetBitmap(width, height, 96, 96, PixelFormats.Pbgra32);
control.UpdateLayout();
bmp.Render(control);
...

The resulting bitmap has the good size but is empty.

Thanks for this great toolkit

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.8</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment] 2017-03-01 01:06
This is finally supported and will be included since the next version of the library(0.9.4), here is an example

https://github.com/beto-rodriguez/Live-Charts/blob/develop/Examples/Wpf/CartesianChart/Chart%20to%20Image/ChartToImageSample.xaml.cs

**Comment by jeanluc-martin** [comment] 2017-03-01 14:17
Hi,
Thanks, I will take a look.

**Closed** 2017-03-09 03:40 UTC
Labels: enhancement

**Comment by omairzia** [comment] 2017-12-18 12:22
Hi,
I have followed the above mentioned link to generate an image of live graph in my application and it is working fine locally but when I deploy it on azure it is not doing anything. I am getting an empty image that does not contains graph in it further I have checked in logs no error or exception is being thrown. It seems that it is not working on Azure.

Can anybody help me please?

**Comment by omairzia** [comment] 2017-12-20 08:03
I can reproduce the issue on my local environment now by just commenting the following line of code:

myChart.Update(true, true); //force chart redraw
viewbox.UpdateLayout();

It seems that control cannot be updated on Azure. I have also tried to update the controls through "Dispatcher" but still getting the same issue on Azure.

Please help me to resolve this issue.

**Comment by tiloc** [comment] 2018-03-01 07:24
Azure app service does not allow GDI calls for security reasons. All offline rendering will fail. You can either get a full virtual machine or a Linux app service.

**Comment by seanvikoren** [comment] 2018-04-05 01:07
Hello Beto, any chance of getting this going under UWP?
