### ISSUE TITLE
Support for .net 4.0 was dropped in 0.7.3

### ISSUE THREAD

**Issue by courchef** [beto-rodriguez/Live-Charts#220] opened 2016-06-22 15:57 UTC
Hi,

I cannot change the version of the .net framework of my WPF project because it breaks my solution.
But I needed the fix for #203... which is present only in 0.7.3

There must be a way to bring back support for .net 4.0.
Could you drop support for .net 4.0 in a separate branch instead of the master branch?

**Comment by beto-rodriguez** [comment] 2016-06-22 16:22
Please see #212, I can compile the code for net 4.0 as I used too, but the problem is that it could throw depending if [KB2468871
](https://www.microsoft.com/en-us/download/details.aspx?id=3556) is installed in your machine.

As I can notice, it is installed in your machine, that is why you don't see the exception in #212, but when you move, or pack your application to a different PC your could see the exception.

0.4.3 is required to keep any application running safety, as far as I know Net 4.0  and 4.0.3 are the same, the migration to the version do not requires any effort. 

Net 4.0.3 is a good patch, it fixes many issues in .net 4.0 and ensures portable libraries run correctly (as in LiveCharts), more info https://support.microsoft.com/en-us/kb/2600211

**Comment by beto-rodriguez** [comment] 2016-06-24 02:29
I will close this issue, hope you understand and agree with me, if not please let me know your opinion.

**Closed by beto-rodriguez** 2016-06-24 02:29 UTC

**Comment by courchef** [comment] 2016-06-25 20:39
i managed to update my project to .net 4.5 so it is all good for me. Thanks

**Comment by GritsenkoSD** [comment] 2016-10-21 12:57
Multi-Targeting Pack for Microsoft .NET Framework 4.0.3 (KB2600213) https://www.microsoft.com/en-us/download/confirmation.aspx?id=29052
