### ISSUE TITLE
Start WPF from console application. WFP UserControl appears to be blank.

### ISSUE THREAD

**Issue by aheroaa** [beto-rodriguez/Live-Charts#383] opened 2016-11-09 11:27 UTC
I'd like to start a WPF window via my console application. I use example code copied frim [Basic Line Chart](https://lvcharts.net/App/examples/v1/wpf/Basic%20Line%20Chart) but not xaml.

In my program.cs. I wrote 3 simple lines like: 
``` C#
var mainWindow = new Window();

mainWindow.Content = new PointShapeLineExample();

mainWindow.Show();
```

The **PointShapeLineExample** class is a UserControl.

But it appears to be blank.

When I append my UserCtrol to the WPF demo MainWindow.xaml. It works good.

Help!

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*0.7.17*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.5*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*windows 10*</td>
</tr>
</table>

**Comment by rusanov-vladimir** [comment] 2016-11-11 09:26
Described behavior seems more like an issue of how you are opening WPF form from console application, rather issue with charts themself, since it's working in WPF demo project. Information you have provided is not enough to reproduce the issue, so I would suggest to close the issue.

**Comment by beto-rodriguez** [comment] 2016-11-11 17:14
I am sorry, this is not an issue with the library, you have to find a way to make it work, it works correctly in WPF, calling it form a console application is out of the scope of this library.

**Closed by beto-rodriguez** 2016-11-11 17:14 UTC
