### ISSUE TITLE
DataToolTip="{x:Null}" causes NRE in designer

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#204] opened 2016-06-13 19:30 UTC
I'm getting an NullReferenceException in the designer when I set the DataToolTip to null for the PieChart.

![croppercapture 2](https://cloud.githubusercontent.com/assets/2676804/16020332/25ebdfe6-3173-11e6-9305-5c420f03b476.png)

Using VS 2013 on Win7

LiveCharts 0.7.1.7
LiveCharts.Wpf 0.7.1.7
LiveChats.Optimizations 0.1.2.1  <-- Note the spelling, beto  :smile:

**Comment by beto-rodriguez** [comment] 2016-06-13 19:47
LiveChats.... this fingers... always doing what they want,,, but be care @gregsdennis Optimizations were desgned to work with 0.5, there are many different things in 0.7, if they don't throw I will be scared.

Thanks for the report.

**Comment by gregsdennis** [comment] 2016-06-13 20:28
So I should probably remove that package then? Are there plans to update it?

**Comment by beto-rodriguez** [comment] 2016-06-13 20:32
Please do, yes.

the target of this library is to be a high performance charting library.

**Comment by gregsdennis** [comment] 2016-06-27 18:01
FYI, just upgraded, still an issue.

LiveCharts Core v0.7.3.1
LiveCharts.Wpf v0.7.3.1

**Comment by beto-rodriguez** [comment] 2016-06-27 18:29
yeah yeah, that is why the issue is open, have not worked on this, thanks for the update

**Comment by beto-rodriguez** [comment] 2016-07-10 16:33
This seems to be fixed with the last commit, I dont' know exactly how I fixed but seems to be fixed, testing and closing when confirmed

**Closed** 2016-07-13 06:49 UTC
Labels: designer, enhancement
