### ISSUE TITLE
LabelFormatter on AxisY for Row graph doesn't work.

### ISSUE THREAD

**Issue by AnisSakkaf-r0631048** [beto-rodriguez/Live-Charts#603] opened 2017-07-20 14:12 UTC
The labelformatter for the XAxis works fine, but when testing the YAxis, it seems that labelformatter is ignored.

```
                var chart = new CartesianChart
                                {
                                    Series = seriesCollection,
                                    Height = 475,
                                    Margin = new Thickness(20),
                                    TooltipTimeout = TimeSpan.Zero,
                                    AxisX =
                                        new AxesCollection
                                            {
                                                new Axis
                                                    {
                                                        Title = "Count",
                                                        FontSize = 16,
                                                        LabelFormatter =
                                                            x => x.ToMetric()
                                                    }
                                            },
                                    AxisY =
                                        new AxesCollection
                                            {
                                                new Axis
                                                    {
                                                        Title = "Filter",
                                                        FontSize = 16,
                                                        Labels = seriesLabels,
                                                        LabelFormatter =
                                                            x => "hey" // This is an example, but it seems it's ignored.
                                                        LabelsRotation = -15
                                                    }
                                            }
```

**Comment by beto-rodriguez** [comment] 2017-10-26 16:13
Hi, I am not able to reproduce this issue, please let me know more about it, also if you could provide a repository with the issue then I can fix it faster.

I am closing this for now, feel free to reply this, or create a new issue if necessary.

**Closed by beto-rodriguez** 2017-10-26 16:13 UTC
