### ISSUE TITLE
geoMap not displaying countries

### ISSUE THREAD

**Issue by TodM0** [beto-rodriguez/Live-Charts#490] opened 2017-03-11 23:05 UTC
#### How to reproduce?

- Download Maps folder and place into application root directory
- Reference LiveCharts, LiveCharts.WinForms, LiveCharts.Wpf
- Place geoMap1 onto Form1

Paste example code:

```C#
        public Form1()
        {
            InitializeComponent();
            var r = new Random();

            var values = new Dictionary<string, double>();

            values["MX"] = r.Next(0, 100);
            values["CA"] = r.Next(0, 100);
            values["US"] = r.Next(0, 100);
            values["IN"] = r.Next(0, 100);
            values["CN"] = r.Next(0, 100);
            values["JP"] = r.Next(0, 100);
            values["BR"] = r.Next(0, 100);
            values["DE"] = r.Next(0, 100);
            values["FR"] = r.Next(0, 100);
            values["GB"] = r.Next(0, 100);

            var lang = new Dictionary<string, string>();
            lang["MX"] = "México"; // change the language if necessary

            geoMap1.HeatMap = values;
            geoMap1.LanguagePack = lang;
            geoMap1.Source = "Maps/World.xml";
        }
```

#### Extra notes

Result:
![image](https://cloud.githubusercontent.com/assets/3946559/23827577/900ca6e2-06ae-11e7-9fec-22a1217d614c.png)

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.4</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>8.1</td>
</tr>
</table>

**Comment by fagenorn** [comment] 2017-03-12 00:56
Maps seems a to be working fine for me, are you sure your refrence to your source is correct?

**Comment by TodM0** [comment] 2017-03-12 01:00
@fagenorn Yes, and I get no errors. I am using VS2015 and I have tried older versions of LiveCharts.

**Comment by beto-rodriguez** [comment] 2017-03-12 02:21
You do not only need to copy the map, you must also set the Build Action to Content

![map build action](https://cloud.githubusercontent.com/assets/10853349/23828471/39f00210-0698-11e7-871d-8b75e947b105.png)


I am closing this for now, I'll update the article in the site soon to explain this.

Thanks for the report, hope this helps you

**Closed by beto-rodriguez** 2017-03-12 02:21 UTC

**Comment by TodM0** [comment] 2017-03-14 12:58
@beto-rodriguez That fixed the issue, thanks. 
A quick question, is there any way to get a list of all of the countries in the geomap/world map, for example:

```C#
            foreach(LiveCharts.Maps.MapData x in geoMap1)
            {
                comboBox1.Items.Add(x.Name);
            }
```

**Comment by atomski-mrav** [comment] 2017-06-16 20:27
I run into the same problem, in my case, it was due to the XML relative path.
```csharp
//geoMap1.Source = "Maps/World.xml";
string exeFile = (new System.Uri(Assembly.GetEntryAssembly().CodeBase)).AbsolutePath;
string exeDir = Path.GetDirectoryName(exeFile);
string fullPath = Path.Combine(exeDir, "..\\..\\Maps\\World.xml");
```

**Comment by rychenga** [comment] 2018-04-24 12:36
I set up  XML relative path. but run into the same problem . I  can't reproduce this example.

**Comment by istavrit** [comment] 2018-10-17 14:17
> @beto-rodriguez That fixed the issue, thanks.
> A quick question, is there any way to get a list of all of the country names in the geomap/world map, for example:
> 
> ```cs
>             foreach(LiveCharts.Maps.MapData x in geoMap1.)
>             {
>                 comboBox1.Items.Add(x.Name);
>             }
> ```
> 
> Also could you give any pointers on how to draw my own maps and generate the required xml path code?

can you solve this problem dude?
