### ISSUE TITLE
LabelFormatter <decimal, string>.ToString("C")

### ISSUE THREAD

**Issue by delvier** [beto-rodriguez/Live-Charts#524] opened 2017-04-12 23:06 UTC
When I tried bind 
LabelFormatter="{Binding YFormatter}" to
Func<decimal,string> YFormatter {get;set;} => value => value.ToString("C"); no effect take place. 
When I changed to <double,string> work as expected.
Am I doing something wrong here ?

#### How to reproduce?
*prepare chart with Y axis that use 
LabelFormatter="{Binding YFormatter}"
Func<decimal,string> YFormatter => value => value.ToString("C"); 

#### I am using
The most recent version* 0.9.5.0

**Comment by beto-rodriguez** [comment] 2017-04-15 22:35
Hi The expected type is `Func<double, string>` the binding is failing because the XAML because it was not able to cast from  `Func<decimal, string>` to  `Func<double, string>`, this is by design, the chart internally uses the `double` type, even the chart is able to plot `decimal` internally everything is `double`.

I hope this makes it clear I am closing this for now, let me know if this was not enough!

**Closed by beto-rodriguez** 2017-04-15 22:35 UTC
