### ISSUE TITLE
Stacked Series visibility Issue

### ISSUE THREAD

**Issue by rohit3d2003** [beto-rodriguez/Live-Charts#172] opened 2016-05-24 18:22 UTC
I am trying to create a Cartesian chart with Stacked Column Series bind to a complex type defined in ViewModel. I have created an Xy Mapper and have configured Y to display a double value. When the Stacked bar series get added, the code is throwing below exception:

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=LiveCharts
  StackTrace:
       at LiveCharts.Configurations.CartesianMapper`1.GetEvaluation(KeyValuePair`2 valuePair)
       at LiveCharts.ChartValues`1.<>c__DisplayClass39_0.<GetLimits>b__0(KeyValuePair`2 data)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at LiveCharts.ChartValues`1.GetLimits()
       at LiveCharts.ChartUpdater.Update(Boolean restartsAnimations)
       at LiveCharts.Wpf.Components.ChartUpdater.UpdaterTick()
       at LiveCharts.Wpf.Components.ChartUpdater.<.ctor>b__0_0(Object sender, EventArgs args)
       at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at Paragon.App.Main() in C:\Projects\Paragon\Paragon\obj\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

Below is a my code:

     var expenseConfig = Mappers.Xy<ExpenseModel>()
                .Y(point => point.Expense);
                
            Expenses = new SeriesCollection(expenseConfig);
            if (Expenses == null) return;
            LabelsForExpense =
                new List<string>(expenses.Item1.Select(e => e.Month).Union(expenses.Item2.Select(p => p.Month)));

            if (expenses.Item1.Count > 0)
            {
                //Actual expense Values
                var actualExpenseValues = new ChartValues<ExpenseModel>();
                foreach (var label in LabelsForExpense)
                {
                    var expenseModel = expenses.Item1.FirstOrDefault(e => e.Month.Equals(label));
                    if (expenseModel != null)
                    {
                        actualExpenseValues.Add(expenseModel);
                    }
                    else
                    {
                        actualExpenseValues.Add(new ExpenseModel
                        {
                            Month = label,
                            Expense = 0
                        });
                    }
                }

                Expenses.Add(new StackedColumnSeries
                {
                    Title = "Actual",
                    Values = actualExpenseValues,
                    DataLabels = true,
                    Stroke = (SolidColorBrush) new BrushConverter().ConvertFrom("#3F51B5"),
                    Fill = (SolidColorBrush) new BrushConverter().ConvertFrom("#3F51B5")
                });
            }

It used to work with 0.6.6 but not sure if I am doing something wrong or its a defect. Also, how do I change the font color of the data labels, currently they are very dim in color and hard to read with top bar printing the value inside the bar making it more difficult to read. The same effect is there in the Live Charts sample for Stacked Bar

**Comment by beto-rodriguez** [comment] 2016-05-24 21:07
Thanks for reporting, fixing soon

**Comment by beto-rodriguez** [comment] 2016-05-25 01:45
Please Indecate X too, I just noticed the new mappers are null by default...

The previous commit initializes them as they used to...

    var expenseConfig = Mappers.Xy<ExpenseModel>()
            .Y(point => point.Expense)
            .X((point, index) => index);

let me know if this soles the issue

**Comment by rohit3d2003** [comment] 2016-05-25 14:09
Mapping X actually resolved the issue but how do I change the font color of the data labels as it is appearing very dim and is hard to read

![image](https://cloud.githubusercontent.com/assets/16943885/15542871/25dc46be-2258-11e6-93bc-c42a677997a9.png)

Also the data labels are appearing inside the top bar line which is even difficult to read. Same thing is happening in Live Charts example which make me believe that it is by design but does not work in my case

**Comment by beto-rodriguez** [comment] 2016-05-25 14:21
Yes I choose that color by design, it is hard to find a good color that works for both, the background of the chart and the background of every bar.

The Foreground of the labels is binded to `Series.Foregorund` property, changing this property will update the labels, even dynamically, please let me know your result and your chosen color I agree with you that it is a bad color in this case.

**Comment by rohit3d2003** [comment] 2016-05-25 14:36
Binding the foreground allows me to change the color but it didn't resolve my issue completely:

1. Data Labels are printed inside the bar making it hard to read.
2. When two bars are stacked, it is very difficult to read the label of the lower/first bar since it is printed between two.

![image](https://cloud.githubusercontent.com/assets/16943885/15543830/08972d54-225c-11e6-8b08-01ff8650e8cb.png)

Now I am thinking of using the bar chart instead of stacked bar series

**Comment by beto-rodriguez** [comment] 2016-05-25 14:41
You are right... actually previous versions did it in another way, I think I should go back to it, being honest with you this was much easier to code :cry:

**Comment by rohit3d2003** [comment] 2016-05-25 14:42
The workaround is to define the max value higher than the max number as per data but that is hard to predict. So in above case, if I define a max value of 700k then the data labels are printed on top of the bar but hard coding it to 700k isn't good and won't work generically

**Comment by beto-rodriguez** [comment] 2016-05-29 02:11
Returned to old labels positioning

whis feature will be included in 0.7.1

![image](https://cloud.githubusercontent.com/assets/10853349/15631028/aa28c678-2518-11e6-8a14-8afdd756a20a.png)

**Closed** 2016-05-29 21:57 UTC
