### ISSUE TITLE
BubblePointView animation can crash application.

### ISSUE THREAD

**Issue by JDemortier** [beto-rodriguez/Live-Charts#196] opened 2016-06-10 09:04 UTC
In `DrawOrMove(ChartPoint previousDrawn, ChartPoint current, int index, ChartCore chart)`, it seems that current can have its ChartLocation.Y set to NaN.

It causes a crash when Ellipse animation is called. I can't seem to reproduce the bug in a standalone example while I can't provide the (private) data that causes the problem.

Even disabling chart animation doesn't prevent the crash.

**Comment by beto-rodriguez** [comment] 2016-06-10 10:40
I will try to look for it, and force it, but the values that causes this would help me a lot

Thanks for reporting the issue

**Comment by JDemortier** [comment] 2016-06-14 08:40
It's quite disturbing, the same values outside of that project don't encounter the NaN problem. So I guess it is a side effect from something else.

Still wondering if it could be useful to check the validity of current.ChartLocation X & Y before calling the animations `Ellipse.BeginAnimation(Canvas.TopProperty, new DoubleAnimation(current.ChartLocation.Y - Diameter*.5, animSpeed));`

**Comment by beto-rodriguez** [comment] 2016-08-08 21:13
Closing this issue, its not confirmed, it was maybe caused by an external issue

**Closed by beto-rodriguez** 2016-08-08 21:13 UTC
Labels: more info required, unconfirmed bug
