### ISSUE TITLE
PieChart not refreshing when Series property is updated through binding

### ISSUE THREAD

**Issue by gregsdennis** [beto-rodriguez/Live-Charts#101] opened 2016-03-21 12:44 UTC
I have the following binding on a PieChart

    Series="{Binding Visuals[0], Converter={x:Static cvtr:MetricToPieSeriesConverter.Instance}}"

The binding recognizes that the target value changes, runs that through the converter, and sets the `Series` property correctly, but the chart doesn't refresh.

**Comment by beto-rodriguez** [comment] 2016-03-22 20:42
Will try and let you know

**Comment by beto-rodriguez** [comment] 2016-04-08 20:23
This should be fixed now, but since you are changing the current series then the charts will not be able to track the changes, they will need to be initialized every time the converter changes the SeriesCollection, this pattern should only be implemented if this is the expected behavior you need.

I added a debug case for this issue in case I messed up something.
https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/z.DebugCases/101

![debug 101](https://cloud.githubusercontent.com/assets/10853349/14396533/c8665e5e-fd9d-11e5-9acc-352daac7846f.gif)

**Closed by beto-rodriguez** 2016-04-08 20:23 UTC
Labels: bug, in progress
