### ISSUE TITLE
Line chart when zoomed data disappears, all sort of artifacts.

### ISSUE THREAD

**Issue by Umbalas** [beto-rodriguez/Live-Charts#111] opened 2016-04-03 17:14 UTC
Line chart when zoomed - data disappears from view, all sort of artifacts when zooming back and forth (only tried with X axis)

The example project fails to work also, as noted.

Side-note:

Love this project ! Exactly what I was searching for and waiting for for my huge C# project ! Keep it up, I will wait for the release !

Please don't hide this secret hi performance library so we could test it.
I am quite new at programming/C# so not much help from me, apart from testing.

Keep it up !

**Comment by beto-rodriguez** [comment] 2016-04-03 18:06
The problem is that 0.6.5 changed this library a lot like 0.6.0 and 0.5.x releases, 0.6.6 (almost ready) will change again some important parts in this code, but I hope it the last major change, at least I don´t see anything else could change in a short future.

Zooming, Panning and high performance charts are directly affected by all those releases I mentioned and its hard to update them every time a big release happens, don´t worry all those features will work again after all major bugs and enhancements are done.

about the high performance algorithms, they are not a secret here is the nuget package https://www.nuget.org/packages/LiveCharts.Optimizations/

and here is an example https://github.com/beto-rodriguez/Live-Charts/tree/master/WPFExamples/HighPerformance

The only problem as I said before because of the major changes this algorithms will not work for 0.6.5, I am not even sure which release works for the algorithms, it must be 0.6.x and I will not work on them till everything is done.

why is it in another package? 

Because I am planning to sell those algorithms in a really low price, compared with some other libraries that their prices are really crazy and go from 500 to 1,000 USD and they don't offer what LiveCharts do.

if it was for me I would work for free in this library because I love it and need it also for another project, but to keep the project alive I need some budget to pay the web site, fix bugs, improve documentation and everything.

**Comment by Umbalas** [comment] 2016-04-04 06:04
Yes, I do understand :) Quite a lot of work is done, I think after this release or/and event half-way till it would be good to focus at polishing the final result.
Now I don't quite get what is where and which features should be stable to use ! I am not rushing anywhere anyway, will use a lot of charts for my hobby project which is huge, so ~6months till I will need a stable charting.

Might just buy that performance lib.

Would be good to have at least a tiny forum for us to be able to ask and you to answer. In future if maintained this could grow enough.

**Comment by beto-rodriguez** [comment] 2016-04-04 14:43
@Umbalas yeah there is the gitter chat, or now I thik it is enough you can join its free :smile: https://gitter.im/beto-rodriguez/Live-Charts

**Comment by beto-rodriguez** [comment] 2016-04-07 15:30
I am closing this issue and adding a new one to explain the issue better

**Closed by beto-rodriguez** 2016-04-07 15:30 UTC
Labels: in progress, To Do
