### ISSUE TITLE
'0' is not a valid value for property 'FontSize'. On Gauge Chart

### ISSUE THREAD

**Issue by R1zwan** [beto-rodriguez/Live-Charts#408] opened 2016-12-08 05:40 UTC
hi beto,
I am getting this error wen the gauge value is set to 0.5 
![image](https://cloud.githubusercontent.com/assets/13550406/20998875/cf64207a-bd36-11e6-89a0-de5c4e4b60fa.png)

**Comment by beto-rodriguez** [comment] 2016-12-16 19:45
Hi, thanks for the report, sadly I was not able to reproduce the error, could you give me a short snippet to illustrate the issue?

**Comment by beto-rodriguez** [comment] 2017-01-15 03:17
Forgot to reference this fix, but I got it while fixing some other issue...

In case you are interested the line that fixes this issue is https://github.com/beto-rodriguez/Live-Charts/commit/c6b09efdbfa6dccf38df7dea32c53724deac5ab6#diff-f177173f397c80bd9ce7bf1cf406bdf4R423

the fix will be included in the next version of the library (0.9)

Thanks for reporting

**Closed by beto-rodriguez** 2017-01-15 03:17 UTC
Labels: more info required
