### ISSUE TITLE
Secondary Values duplicating on barchart

### ISSUE THREAD

**Issue by lrmills85** [beto-rodriguez/Live-Charts#19] opened 2015-10-02 01:00 UTC
So I have a bar chart the following:

Primary Values = Assigned, In Progress
Secondary Values = 876, 119

When I add this to the chart I see this...

![image](https://cloud.githubusercontent.com/assets/14826876/10237402/04038eb4-687f-11e5-9a91-57bc853fd555.png)

But I have zoom enabled and when I zoom it changes to this...

![image](https://cloud.githubusercontent.com/assets/14826876/10237413/210ca91e-687f-11e5-8b6b-3be7e3fd9662.png)

it does the same thing when zoom is disabled but it will always look like the first screenshot.

**Comment by beto-rodriguez** [comment] 2015-10-02 02:36
Sorry but I am not able to reproduce this. This should not heppen since I Implemented the method `ConfigureSmartAxis`. If you enable secondaryaxis separator you will understand what the problem is, by default line, bar and stacked bar charts force a separator equals to 1 but in your case it is setting a step of .5 thats why you get 2 labels. Can you please give me more info, or Fork this and reproduce the error there, or try to see what happens in this method https://github.com/beto-rodriguez/Live-Charts/blob/master/Charts/Charts/Chart.cs#L287

**Comment by beto-rodriguez** [comment] 2015-10-13 05:13
closing issue since no more info

**Closed by beto-rodriguez** 2015-10-13 05:13 UTC
Labels: bug
