### ISSUE TITLE
System.NullReferenceException  in Winforms Examples

### ISSUE THREAD

**Issue by chucklu** [beto-rodriguez/Live-Charts#244] opened 2016-07-08 01:10 UTC
Live-Charts\Examples\WinForms\Main.cs
private void LabelsOnClick(object sender, EventArgs e)
        {
            new Labels().ShowDialog();
        }

**Comment by chucklu** [comment] 2016-07-08 01:11
An unhandled exception of type 'System.NullReferenceException' occurred in LiveCharts.dll

**Comment by beto-rodriguez** [comment] 2016-07-08 21:51
Try pulling the most recent version of this library, it works correctly in the current repo version

**Comment by chucklu** [comment] 2016-07-09 14:18
I have fetch and merge the latest source code
the problem still exist
the latest log is 
commit 7eff6e2ba806ce7e1de77240938399c593725117
Author: Alberto Rodríguez <rodriguezo.alberto@gmail.com>
Date:   Wed Jul 6 12:42:22 2016 -0500

    Update README.md

**Comment by beto-rodriguez** [comment] 2016-07-09 14:44
it works for me, please let me know what you are doing to throw the exception, you target framework and the full exception please, so I can help you better

![test](https://cloud.githubusercontent.com/assets/10853349/16708442/ac3218fe-45b9-11e6-966a-8e9f15dc414b.gif)

**Comment by chucklu** [comment] 2016-07-09 15:23
target framework is .net 4.5
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=未将对象引用设置到对象的实例。
  Source=LiveCharts
  StackTrace:
       在 LiveCharts.ChartFunctions.FromPlotArea(Double value, AxisOrientation source, ChartCore chart, Int32 axis)
       在 LiveCharts.ChartFunctions.FromDrawMargin(Double value, AxisOrientation source, ChartCore chart, Int32 axis)
       在 LiveCharts.Wpf.Charts.Base.Chart.OnDraggingStart(Object sender, MouseButtonEventArgs e)
       在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       在 System.Windows.Input.InputManager.ProcessStagingArea()
       在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.RunDialog(Form form)
       在 System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
       在 System.Windows.Forms.Form.ShowDialog()
       在 Winforms.Main.btnLabels_Click(Object sender, EventArgs e) 位置 D:\SourceCode\GitHub\Live-Charts\Examples\WinForms\Main.cs:行号 39
       在 System.Windows.Forms.Control.OnClick(EventArgs e)
       在 System.Windows.Forms.Button.OnClick(EventArgs e)
       在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       在 System.Windows.Forms.Control.WndProc(Message& m)
       在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
       在 System.Windows.Forms.Button.WndProc(Message& m)
       在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       在 System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.Run(Form mainForm)
       在 Winforms.Program.Main() 位置 D:\SourceCode\GitHub\Live-Charts\Examples\WinForms\Program.cs:行号 19
       在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       在 System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by chucklu** [comment] 2016-07-09 15:25
since the winforms project use nuget to get the dll
<package id="LiveCharts" version="0.7.4" targetFramework="net45" />
I can not debug this problem

maybe, I can add project as reference

**Comment by chucklu** [comment] 2016-07-09 15:27
ok,I have found the problem,I'll try to fix it later

**Comment by chucklu** [comment] 2016-07-09 15:43
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=未将对象引用设置到对象的实例。
  Source=LiveCharts
  StackTrace:
       在 LiveCharts.ChartFunctions.FromPlotArea(Double value, AxisOrientation source, ChartCore chart, Int32 axis) 位置 D:\SourceCode\GitHub\Live-Charts\Core\ChartFunctions.cs:行号 132
       在 LiveCharts.ChartFunctions.FromDrawMargin(Double value, AxisOrientation source, ChartCore chart, Int32 axis) 位置 D:\SourceCode\GitHub\Live-Charts\Core\ChartFunctions.cs:行号 217
       在 LiveCharts.Wpf.Charts.Base.Chart.OnDraggingStart(Object sender, MouseButtonEventArgs e) 位置 D:\SourceCode\GitHub\Live-Charts\WpfView\Charts\Base\Chart.ZoomPan.cs:行号 52
       在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
       在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       在 System.Windows.Input.InputManager.ProcessStagingArea()
       在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.RunDialog(Form form)
       在 System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
       在 System.Windows.Forms.Form.ShowDialog()
       在 Winforms.Main.btnLabels_Click(Object sender, EventArgs e) 位置 D:\SourceCode\GitHub\Live-Charts\Examples\WinForms\Main.cs:行号 39
       在 System.Windows.Forms.Control.OnClick(EventArgs e)
       在 System.Windows.Forms.Button.OnClick(EventArgs e)
       在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       在 System.Windows.Forms.Control.WndProc(Message& m)
       在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
       在 System.Windows.Forms.Button.WndProc(Message& m)
       在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       在 System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       在 System.Windows.Forms.Application.Run(Form mainForm)
       在 Winforms.Program.Main() 位置 D:\SourceCode\GitHub\Live-Charts\Examples\WinForms\Program.cs:行号 19
       在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       在 System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by chucklu** [comment] 2016-07-09 15:52
sorry,I knew little about tis project ,I can not fix this.
the problem is located under  Live-Charts\Core\ChartFunctions.cs
 public static double FromPlotArea(double value, AxisOrientation source, ChartCore chart, int axis = 0)
line number in file is 132
   p1.X = chart.AxisX[axis].MaxLimit;
it seems the AxisX of chart is null

**Comment by beto-rodriguez** [comment] 2016-07-09 16:42
So you can even run the application? this throws when the app starts?

**Comment by chucklu** [comment] 2016-07-09 17:05
yes, I can run the application
the exception throw when I try to open the labels
Winforms.Main.btnLabels_Click(Object sender, EventArgs e) 位置 D:\SourceCode\GitHub\Live-Charts\Examples\WinForms\Main.cs:行号 39

**Comment by beto-rodriguez** [comment] 2016-07-11 18:07
I found an error with the Winforms nuget packages in 0.7.4.1      0.7.5 it is now fixed in 0.7.5.1 please try updating the nuget package, it should work correctly now

**Comment by chucklu** [comment] 2016-07-12 01:22
@beto-rodriguez  the labels works fine now
I find the same problem exist when I try to oepn the BasicLineExample

**Comment by chucklu** [comment] 2016-07-12 01:24
weird,I find this bug can not be reproduced everytime

**Comment by beto-rodriguez** [comment] 2016-07-12 01:32
mmm, interesting, please ensure you pulled the latest vesrion of this repo, I removed that ugly nuget dependency, they are now referenced to the source code projects, so you will see exactly where it throws

**Comment by chucklu** [comment] 2016-07-12 01:45
I am pretty sure,I have already fetch and merge the latest code of master
the latest commit log is this one 

commit 59785d139b8a67491d3451089890a00dc8c3c40c
Author: beto rodriguez <rodriguezo.alberto@gmail.com>
Date:   Mon Jul 11 16:42:14 2016 -0500

    pie and doughnut examples with website

**Comment by chucklu** [comment] 2016-07-12 02:07
在 LiveCharts.ChartFunctions.FromPlotArea(Double value, AxisOrientation source, ChartCore chart, Int32 axis) 位置 D:\SourceCode\GitHub\Live-Charts\Core\ChartFunctions.cs:行号 132
在 LiveCharts.ChartFunctions.FromDrawMargin(Double value, AxisOrientation source, ChartCore chart, Int32 axis) 位置 D:\SourceCode\GitHub\Live-Charts\Core\ChartFunctions.cs:行号 217
在 LiveCharts.Wpf.Charts.Base.Chart.OnDraggingStart(Object sender, MouseButtonEventArgs e) 位置 D:\SourceCode\GitHub\Live-Charts\WpfView\Charts\Base\Chart.ZoomPan.cs:行号 52

I find this in StackTrace of the exception,OnDraggingStart
  DrawMargin.MouseDown += OnDraggingStart;
  internal Canvas DrawMargin { get; set; }

maybe,I find the reason for this bug.
it happened with location of the form.
when you try show the dialog of  Labels
 private void btnLabels_Click(object sender, EventArgs e)
        {
            new Labels().ShowDialog();
        }
my mouse is located just upon the location of the form,and the MouseDown Event was triggered

**Comment by chucklu** [comment] 2016-07-12 02:09
I  have tested,when I move the main form, to make sure the location of Labels form will not covered by the mouse.
the System.NullReferenceException will not throw

**Comment by beto-rodriguez** [comment] 2016-07-14 19:16
@chucklu it is really frustrating I can reproduce this error :cry:

**Comment by chucklu** [comment] 2016-07-15 01:32
@beto-rodriguez  It seems after double click ,when the new form show, the canvas catch mouse down event

**Comment by beto-rodriguez** [comment] 2016-07-22 17:03
@chucklu Awesome! I finally got the error, I just fixed it, this will be included in the next release of the library

Thanks for reporting!

**Closed** 2016-07-22 17:04 UTC
