### ISSUE TITLE
Changing properties crashes Visual Studio (2013/2015/2017)

### ISSUE THREAD

**Issue by TechCowboy** [beto-rodriguez/Live-Charts#502] opened 2017-03-17 17:52 UTC
#### How to reproduce?

Here's my step-by-step crash reproduction with cartesianChart in a WinForm application

Place Cartesian Chart on Form

1) In properties under 'Misc' Click on AxisY 
2) Click on the '...' 
3) Change MaxValue from NaN to 100 
4) Click OK -- immediate crash and visual studio restarts*

#### Extra notes

I've also tried setting the MinValue from NaN to 0 at the same time to see if that solved it, but it did not.

#### I am using

Visual Studio 2013 Community
Visual Studio 2015 Community
Visual Studio 2017 Enterprise

**Comment by beto-rodriguez** [comment] 2017-03-19 01:56
I was not able to reproduce, I am using VS 2015 CE, it didn't throw, but the axis limit was not set properly.

If anyone is facing this issue do no use the designer to add axes for now, instead do it from code behind: 

```c#
cartesianChart1.AxisY.Add(new Axis
            {
                MinValue = -1,
                MaxValue = 1,
                LabelFormatter = _vm.YFormatter,
                Separator = new Separator
                {
                    Stroke = new SolidColorBrush(Color.FromRgb(235,235,235))
                }
            });
```

**Comment by beto-rodriguez** [comment] 2017-06-20 01:57
I will close this now, the library works fine with WinForms, considering that we also have more solid options  like WPF and UWP to have a better support the Designer (WinForms) requires a considerable amount of work, and I personally don't think it is worth.

**Closed by beto-rodriguez** 2017-06-20 01:57 UTC
Labels: bug, has workaround, WinForms

**Comment by king612** [comment] 2017-07-25 02:47
Well I just started using LiveCharts and love it so far.  But I am stuck doing WinForms, and the poster is right - in VS 2017 community, touching anything in designer crashes VS.  Here's one vote for continuing to support WinForms in VS 2017 LiveCharts!

Thanks for the great work.

**Comment by skinnyMan** [comment] 2017-07-31 20:30
This is definitely an issue in VS 2015, WinForms is still very relevant.
