### ISSUE TITLE
Can't set some properties via stlyles

### ISSUE THREAD

**Issue by Dvornik** [beto-rodriguez/Live-Charts#349] opened 2016-10-06 09:18 UTC
#### How to reproduce?

``` xaml
<wpf:Gauge Width="100"
                   Height="100"
                   From="0"
                   LabelFormatter="{Binding PercentageFormatter}"
                   To="100"
                   Uses360Mode="True"
                   Value="{Binding PercentageOfJustInTimeFulfilledOrders}" >
            <wpf:Gauge.Style >
                <Style TargetType="wpf:Gauge">
                    <Setter Property="GaugeBackground" Value="Red" />  
                    <Setter Property="ToColor" Value="Green" />
                    <Setter Property="FromColor" Value="Aqua" />
                    <Setter Property="Height" Value="34"></Setter>
                </Style>
            </wpf:Gauge.Style>
</wpf:Gauge>

```

GaugeBackground, ToColor, FromColor does not applied via styles (not only inline styles, of course). 
#### I am using

WPF

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.7.16</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10 x64</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment] 2016-11-02 02:43
Hi, I am not able to reproduce this issue, please let me know more about it, also if you could provide a repository with the issue then I can fix it faster.

Thanks for the feedback btw.

In the next gif I use the designer to test it, but it also works in run time, please try with 0.7.17 version, also ensure you are not overriding the the styles somewhere else.

I tried with the example in the web site and just pasted your style, it is working correctly.

I will close this issue just because I am about to release 0.8 and I don't like to see all this issues before a release 😢, but please feel free to add any feedback or comments to this or any other new issue

Thanks!

![new](https://cloud.githubusercontent.com/assets/10853349/19914865/de911718-a073-11e6-9b94-807dfbf79f99.gif)

**Closed by beto-rodriguez** 2016-11-02 02:43 UTC

**Comment by nalex177** [comment] 2018-04-23 12:14
**@Dvornik,**
could you give a code behind of your example?
I've started learning WPF on the last week . I need use percentage gauge, but I can't understand how to do this by using bindings.
Thank you!
